services:
  db:
    image: postgres:16-alpine
    container_name: filo_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "23456781"
      POSTGRES_DB: filo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d filo"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: